build: remove initializers for pmix_*_t
Problem: flux-pmix can't be built with gcc 4.9.3 or 4.8.4 (and
presumably other compilers in the 4.x series) due to initialization
errors such as:

 main.c:138:5: error: missing braces around initializer
     pmix_info_t info[2] = { 0 };
     ^
 main.c:247:5: error: missing braces around initializer
     pmix_proc_t proc = { 0 };
     ^
These structures are typically not used uninitialized, so the
intializers are most likely unnecessary. Remove initializers to remove
these errors as per @garlick.